"Pricing" Section Updated Alignments
CatsInTech/GitHub-ReadMe pull request #104
Opened 2023-06-05 21:26 UTC by iamRabia-N

This PR contains the updated code of the "Pricing" Section Alignments. This PR is the result of the following issue:
[New Feature_WebApp] - Pricing Section Text Alignment #103

Closes #103

## Proposed Changes
Alignment of the content in center to make this section's alignment consistent with the overall website.
## Type of Change

- [ ] New Feature (Landing Page)
- [ ] New Feature (App)
- [ ] Bug (Landing Page)
- [ ] Bug (App)
- [ ] New Component (App)
- [x] Enhancement
- [ ] Documentation / ReadMe / Workflows
- [ ] Other (If not in above options):  

## Your Idea for Level (GSSoC)

- [x] Level 1
- [ ] Level 2
- [ ] Level 3

## Screenshots (if applicable)
![github-readme pr](https://github.com/CatsInTech/GitHub-ReadMe/assets/115794049/48879e43-02be-4712-8c25-d0c181ee9da6)

2023-06-05 23:09 UTC, praveenscience requested changes
Revert the library files.

2023-06-05 23:09 UTC, praveenscience commented on css/bootstrap.min.css
Don't touch the library files.

2023-06-06 15:41 UTC, iamRabia-N commented
Hi @praveenscience
I have reverted commit but both files are removed. Now is it okay if I'll share new commit (with no modification in library files) in the same branch or should I go with new branch?

2023-06-07 00:42 UTC, praveenscience commented
I guess so. How did you manage to pull up a PR that contains no changed files? 🤣 @iamRabia-N

2023-06-07 00:43 UTC, praveenscience commented
Oh, you reverted the whole commit? 🤯

2023-06-07 03:55 UTC, iamRabia-N commented
Those 2 files were together under one commit. Reverting commit removed both files.

2023-06-07 03:57 UTC, iamRabia-N commented
@praveenscience I am going to close this PR and create another one to push changes for sake of clarity.

2023-06-07 19:20 UTC, iamRabia-N commented
Hi @praveenscience 
Kindly review the latest commit with name "Updated Pricing Section" which contains the modified code related to the issue.

2023-06-12 16:56 UTC, iamRabia-N commented
@praveenscience Kindly review the changes and share your feedback

2023-06-23 19:19 UTC, iamRabia-N commented
> @praveenscience Kindly review the changes and share your feedback

@praveenscience

2025-11-18 18:46 UTC, closed without merging