Fixes #48
CatsInTech/GitHub-ReadMe pull request #69
Opened 2023-06-01 05:31 UTC by mukul314

Fixes issue #48

2023-06-03 18:00 UTC, AmanJain18 commented
@mukul314  Edit this PR template and rewrite it properly

2023-06-04 05:10 UTC, mukul314 commented
> @mukul314 Edit this PR template and rewrite it properly

@AmanJain18 done!

2023-06-04 08:36 UTC, AmanJain18 commented
Also fix the title bro.

2023-06-04 12:29 UTC, praveenscience requested changes

2023-06-04 12:29 UTC, praveenscience commented on README.md
> +</div>
Can we have this aligned properly, thanks! 😊

2023-06-04 22:02 UTC, praveenscience requested changes

2023-06-04 22:02 UTC, praveenscience commented on README.md
> +  <p>
Do we require the `<p>` tag?

2023-06-04 22:02 UTC, praveenscience commented on README.md
> +  </p>
Also, can you move it below the ToC?

2023-06-05 19:45 UTC, praveenscience requested changes

2023-06-05 19:45 UTC, praveenscience commented on README.md
> +<br>
Amazing, please kindly indent. 😊 I'll merge it ASAP. Use `<br />` as well instead of `<br>`. Thanks.

2023-06-05 22:52 UTC, praveenscience commented
@AmanJain18 It's alright, @mukul314 is trialling a lot of things and then again, getting merge conflicts and stuff! 😅

2023-06-05 22:56 UTC, AmanJain18 commented
Ya No Issues. 😊🤗

2023-06-06 02:19 UTC, mukul314 commented
> For just adding badges in readme, this much Commits? 😂🤦

@AmanJain18 🤣 , I know that this issue has been stretched a bit, but I learned a lot from it also. Along with that, I would also like to thank amazing maintainers like @praveenscience and you who have patiently reviewed each and every request and responded timely. The guidance that I received is remarkable. Thanks a lot for that 😄 .

As for the changes, I will replace the <br> with </br> but can you tell me how to keep that indentation part? I guess I am not getting what you want to convey 😅 .

2023-06-07 00:36 UTC, praveenscience approved these changes
Never mind, @mukul314, I have made it myself, check it out from the changes! 💪

2023-06-07 00:36 UTC, praveenscience commented on README.md
> +<br>
Never mind, I did it myself. 😊

2023-06-07 00:36 UTC, merged