DropDown from Home tag is removed.
CatsInTech/GitHub-ReadMe pull request #77
Opened 2023-06-02 10:17 UTC by Khushisharma23

## Related Issue(s)

 It Closes #56 

## Proposed Changes
 Home Tag had an unwanted dropdown menu so I removed it.

## Type of Change

- [ ] New Feature (Landing Page)
- [ ] New Feature (App)
- [x] Bug (Landing Page)
- [ ] Bug (App)
- [ ] New Component (App)
- [ ] Enhancement
- [ ] Documentation / ReadMe / Workflows
- Other (If not in above options):  

## Your Idea for Level (GSSoC)

- [ ] Level 1
- [x] Level 2
- [ ] Level 3

## Screenshots (if applicable)
 ###Before Changes
![image](https://github.com/CatsInTech/GitHub-ReadMe/assets/98320438/9c260538-3a91-4cf8-91f6-630351ab67f8)
###After Changes
![image](https://github.com/CatsInTech/GitHub-ReadMe/assets/98320438/cf24f9ca-46be-49d5-b6b6-9713a88936fe)

2023-06-02 10:58 UTC, praveenscience requested changes
Can you get rid of the `.vscode` folder?

2023-06-02 10:58 UTC, praveenscience commented
Use `prettier-width: 800000` as well, thanks! 😊

2023-06-02 11:03 UTC, Khushisharma23 commented
Yup let me remove it

2023-06-03 12:24 UTC, praveenscience requested changes

2023-06-03 12:24 UTC, praveenscience commented on index.html
>                    </li>
Why is there an empty tag here?

2023-06-03 13:02 UTC, Khushisharma23 commented
This PR is totally ruined. Sorry! :)

2023-06-03 13:02 UTC, closed without merging

2023-06-03 13:11 UTC, praveenscience commented
Failure is the stepping stone to success! 💪