Added hover effect on navbar items which fixes #68
CatsInTech/GitHub-ReadMe pull request #89
Opened 2023-06-03 13:25 UTC by mukul314

## Related Issue(s)

## Proposed Changes

## Type of Change

- [ ] New Feature (Landing Page)
- [ ] New Feature (App)
- [ ] Bug (Landing Page)
- [ ] Bug (App)
- [ ] New Component (App)
- [ ] Enhancement
- [ ] Documentation / ReadMe / Workflows
- Other (If not in above options):  

## Your Idea for Level (GSSoC)

- [ ] Level 1
- [ ] Level 2
- [ ] Level 3

## Screenshots (if applicable)

## Additional Notes

2023-06-03 13:42 UTC, praveenscience requested changes
Use the right PR template, thanks.

2023-06-03 16:37 UTC, mukul314 commented
> Use the right PR template, thanks.

I edited that, is it okay now @praveenscience ?

2023-06-03 17:58 UTC, praveenscience requested changes

2023-06-03 17:58 UTC, praveenscience commented on css/style.css
> +  padding: 5px 10px;
Can we have these two in the main `a`?

2023-06-04 04:32 UTC, mukul314 commented on css/style.css
> +  padding: 5px 10px;
Okay I'll do that.

2023-06-04 12:28 UTC, praveenscience commented on css/style.css
> +  padding: 5px 10px;
Correct! 😊

2023-06-04 22:04 UTC, praveenscience requested changes

2023-06-04 22:04 UTC, praveenscience commented on css/style.css
> +
Remove this line.

2023-06-04 22:04 UTC, praveenscience commented on css/style.css
> +.navbar-nav.ml-auto.menu li a{
Add space after `a`.

2023-06-04 22:04 UTC, praveenscience commented on css/style.css
> +  color: #ffffff;
Make it `#fff`

2023-06-05 19:42 UTC, praveenscience approved these changes
👍

2023-06-05 19:43 UTC, merged